package com.model;

// Generated 20-oct-2013 14:49:17 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Counselor generated by hbm2java
 */
@Entity
@Table(name = "Counselor", catalog = "ifpwafcad_dbo")
public class Counselor implements java.io.Serializable{

	private static final long serialVersionUID = -6036206357708335606L;
	private Short counselorId;
	private String firstName;
	private String nickName;
	private String lastName;
	private String telephone;
	private String email;
	private Date memberSince;

	public Counselor(){}

	public Counselor(String firstName, String nickName, String lastName, String telephone, String email, Date memberSince){
		this.firstName = firstName;
		this.nickName = nickName;
		this.lastName = lastName;
		this.telephone = telephone;
		this.email = email;
		this.memberSince = memberSince;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "counselor_id", unique = true, nullable = false)
	public Short getCounselorId(){
		return this.counselorId;
	}

	public void setCounselorId(Short counselorId){
		this.counselorId = counselorId;
	}

	@Column(name = "first_name", length = 50)
	public String getFirstName(){
		return this.firstName;
	}

	public void setFirstName(String firstName){
		this.firstName = firstName;
	}

	@Column(name = "nick_name", length = 50)
	public String getNickName(){
		return this.nickName;
	}

	public void setNickName(String nickName){
		this.nickName = nickName;
	}

	@Column(name = "last_name", length = 50)
	public String getLastName(){
		return this.lastName;
	}

	public void setLastName(String lastName){
		this.lastName = lastName;
	}

	@Column(name = "telephone", length = 25)
	public String getTelephone(){
		return this.telephone;
	}

	public void setTelephone(String telephone){
		this.telephone = telephone;
	}

	@Column(name = "email", length = 50)
	public String getEmail(){
		return this.email;
	}

	public void setEmail(String email){
		this.email = email;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "member_since", length = 10)
	public Date getMemberSince(){
		return this.memberSince;
	}

	public void setMemberSince(Date memberSince){
		this.memberSince = memberSince;
	}

}
