package com.model;

// Generated 20-oct-2013 14:49:17 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "Subject", catalog = "ifpwafcad_dbo")
public class Subject implements java.io.Serializable{
	
	private static final long serialVersionUID = 5899293103284689323L;
	private Short subjectId;
	private String name;
	private String description;
	private Short counselorIdfk;

	public Subject(){}

	public Subject(String name, String description, Short counselorIdfk){
		this.name = name;
		this.description = description;
		this.counselorIdfk = counselorIdfk;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "subject_id", unique = true, nullable = false)
	public Short getSubjectId(){
		return this.subjectId;
	}

	public void setSubjectId(Short subjectId){
		this.subjectId = subjectId;
	}

	@Column(name = "name", length = 50)
	public String getName(){
		return this.name;
	}

	public void setName(String name){
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription(){
		return this.description;
	}

	public void setDescription(String description){
		this.description = description;
	}

	@Column(name = "counselor_idfk")
	public Short getCounselorIdfk(){
		return this.counselorIdfk;
	}

	public void setCounselorIdfk(Short counselorIdfk){
		this.counselorIdfk = counselorIdfk;
	}

}
